apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-ecom-config
data:
  SPRING_APPLICATION_NAME: "Sb-Ecom"
  SERVER_PORT: "9090"

  DB_URL: "jdbc:postgresql://postgres:5432/ecommerce"
  DB_USERNAME: "postgres"

  HIBERNATE_DDL_AUTO: "update"
  HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

  PROJECT_IMAGE_PATH: "images/"

  JWT_EXPIRATION: "3000000"
  JWT_COOKIE_NAME: "springBootEcom"

  FRONTEND_URL: "http://localhost:5173"
  IMAGE_BASE_URL: "http://localhost:9090/images"