apiVersion: v1
kind: Secret
metadata:
  name: sb-ecom-secret
type: Opaque
stringData:
  DB_PASSWORD: "test123"
  JWT_SECRET: "dummy_jwt_secret"
  STRIPE_SECRET_KEY: "dummy_stripe_key"
  POSTGRES_PASSWORD: "test123"